<a href="https://colab.research.google.com/github/XueyanZhang/huggingface/blob/master/NLP_course/Behind_the_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Behind the pipeline (PyTorch)

Install the Transformers, Datasets, and Evaluate libraries to run this notebook.

In [1]:
!pip install datasets evaluate transformers[sentencepiece]

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 519.6/519.6 kB 5.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.4/81.4 kB 5.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 23.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 kB 15.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 23.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 13.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.9/294.9 kB 28.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 38.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 64.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 65.5 MB/s eta 0:00:00


In [2]:
from transformers import pipeline

classifier = pipeline("sentiment-analysis")
classifier(
    [
        "I've been waiting for a HuggingFace course my whole life.",
        "I hate this so much!",
    ]
)

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


[{'label': 'POSITIVE', 'score': 0.9598048329353333},
 {'label': 'NEGATIVE', 'score': 0.9994558691978455}]

In [3]:
from transformers import AutoTokenizer

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

In [4]:
raw_inputs = [
    "I've been waiting for a HuggingFace course my whole life.",
    "I hate this so much!",
]
inputs = tokenizer(raw_inputs, padding=True, truncation=True, return_tensors="pt")
print(inputs)

{'input_ids': tensor([[  101,  1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,
          2607,  2026,  2878,  2166,  1012,   102],
        [  101,  1045,  5223,  2023,  2061,  2172,   999,   102,     0,     0,
             0,     0,     0,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]])}


In [5]:
from transformers import AutoModel

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
model = AutoModel.from_pretrained(checkpoint)

In [6]:
outputs = model(**inputs)
print(outputs.last_hidden_state.shape)
print(outputs["last_hidden_state"])
print(outputs[0])

torch.Size([2, 16, 768])
tensor([[[-0.1798,  0.2333,  0.6321,  ..., -0.3017,  0.5008,  0.1481],
         [ 0.2758,  0.6497,  0.3200,  ..., -0.0760,  0.5136,  0.1329],
         [ 0.9046,  0.0985,  0.2950,  ...,  0.3352, -0.1407, -0.6464],
         ...,
         [ 0.1466,  0.5661,  0.3235,  ..., -0.3376,  0.5100, -0.0561],
         [ 0.7500,  0.0487,  0.1738,  ...,  0.4684,  0.0030, -0.6084],
         [ 0.0519,  0.3729,  0.5223,  ...,  0.3584,  0.6500, -0.3883]],

        [[-0.2937,  0.7283, -0.1497,  ..., -0.1187, -1.0227, -0.0422],
         [-0.2206,  0.9384, -0.0951,  ..., -0.3643, -0.6605,  0.2407],
         [-0.1536,  0.8988, -0.0728,  ..., -0.2189, -0.8528,  0.0710],
         ...,
         [-0.3017,  0.9002, -0.0200,  ..., -0.1082, -0.8412, -0.0861],
         [-0.3338,  0.9674, -0.0729,  ..., -0.1952, -0.8181, -0.0634],
         [-0.3454,  0.8824, -0.0426,  ..., -0.0993, -0.8329, -0.1065]]],
       grad_fn=<NativeLayerNormBackward0>)
tensor([[[-0.1798,  0.2333,  0.6321,  ..., -0.30

In [7]:
from transformers import AutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)
outputs = model(**inputs)

In [8]:
print(outputs.logits.shape)

torch.Size([2, 2])


In [9]:
print(outputs.logits)

tensor([[-1.5607,  1.6123],
        [ 4.1692, -3.3464]], grad_fn=<AddmmBackward0>)


Those are not probabilities but logits, the raw, unnormalized scores outputted by the last layer of the model. To be converted to probabilities, they need to go through a SoftMax layer

In [10]:
import torch

predictions = torch.nn.functional.softmax(outputs.logits, dim=-1)
print(predictions)

tensor([[4.0195e-02, 9.5980e-01],
        [9.9946e-01, 5.4418e-04]], grad_fn=<SoftmaxBackward0>)


In [11]:
model.config.id2label

{0: 'NEGATIVE', 1: 'POSITIVE'}

# Tryout
Choose two (or more) texts of your own and run them through the **"zero-shot-classification"** pipeline. Then replicate the steps you saw here yourself and check that you obtain the same results!

In [12]:
from transformers import pipeline

classifier = pipeline("zero-shot-classification")
classifier(
    "iPad Air with an M1 chip is the best value in 2023",
    candidate_labels=["education", "politics", "business", "techs"],
)

No model was supplied, defaulted to facebook/bart-large-mnli and revision c626438 (https://huggingface.co/facebook/bart-large-mnli).
Using a pipeline without specifying a model name and revision in production is not recommended.


{'sequence': 'iPad Air with an M1 chip is the best value in 2023',
 'labels': ['techs', 'business', 'education', 'politics'],
 'scores': [0.5945318341255188,
  0.28668442368507385,
  0.07616250216960907,
  0.04262123256921768]}

## replication w/ tokenizer + model

In [13]:
from transformers import AutoTokenizer

checkpoint2 = "facebook/bart-large-mnli"
tokenizer2 = AutoTokenizer.from_pretrained(checkpoint2)

In [17]:
raw_inputs2 = "iPad Air with an M1 chip is the best value in 2023"
candidate_labels=["education", "politics", "business", "techs"]
inputs2 = tokenizer2(raw_inputs2, padding=True, truncation=True, return_tensors="pt")
print(inputs2)

{'input_ids': tensor([[    0,   118, 28874,  1754,    19,    41,   256,   134,  6638,    16,
             5,   275,   923,    11,   291,  1922,     2]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}


In [19]:
from transformers import AutoModel

model = AutoModel.from_pretrained(checkpoint2)
outputs = model(**inputs)

In [21]:
print(outputs)

Seq2SeqModelOutput(last_hidden_state=tensor([[[-0.8849,  1.5460, -0.6531,  ...,  0.0313, -0.5359, -1.8533],
         [-0.9057,  2.5259, -1.7790,  ..., -0.0177, -1.3409, -0.9762],
         [-0.0253,  2.0373, -0.6625,  ...,  0.1807,  0.4623, -2.1846],
         ...,
         [ 0.9897,  1.8092, -1.3533,  ...,  0.1032,  0.0178, -1.1464],
         [-0.3863,  0.9239, -0.3241,  ..., -0.9860,  0.2154, -0.6463],
         [ 0.8442,  1.4853, -1.4546,  ...,  0.1002,  0.1109, -1.1008]],

        [[-0.8316,  0.9431, -0.3405,  ..., -0.2087,  0.1133, -1.1944],
         [-1.0256,  1.5175, -1.5258,  ..., -0.1362, -0.3762, -0.5396],
         [-0.6447,  1.2285, -0.4191,  ..., -0.5901,  0.2295, -1.4497],
         ...,
         [ 0.5328,  0.6694, -1.0032,  ...,  0.6029, -0.0903, -0.7080],
         [ 0.5388,  0.7217, -1.0754,  ...,  0.6392, -0.0578, -0.6872],
         [ 0.5332,  0.7664, -1.1380,  ...,  0.6728, -0.0228, -0.6873]]],
       grad_fn=<NativeLayerNormBackward0>), past_key_values=((tensor([[[[ 0.356